version: 2.1
jobs:
  build_and_publish_docs:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - run:
          name: Install Linux dependencies
          command: apk update && apk add autoconf libtool automake
      - run:
          name: Install dependencies
          command: cd docs/website && yarn
      - run:
          name: Build docs website
          command: cd docs/website && yarn build
      - run:
          name: Deploy to Firebase
          command: cd docs/website && ./node_modules/.bin/firebase deploy --token "$DOCS_FIREBASE_TOKEN"
  build_and_publish:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build plugin
          command: yarn build:plugin
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: cd gatsby-theme-localization && npm publish --tag $(node get-tag.js)
  unit_test:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Unit test
          command: yarn test
  e2e_test:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: E2E Test
          command: yarn test:e2e
workflows:
  version: 2
  test:
    jobs:
      - unit_test
      - e2e_test
  build_and_publish_docs:
    jobs:
      - build_and_publish_docs:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^docs.*$/
  build_and_publish:
    jobs:
      - unit_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
      - e2e_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
      - build_and_publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
          requires:
            - unit_test
            - e2e_test
  
